name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npx cypress run --reporter mochawesome

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: cypress-report
        path: cypress/reports

    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        subject: Cypress Test Report
        body: |
          Hi,  
          The Cypress test has completed. Find the attached report.
        to: your-email@example.com
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: cypress/reports/*.html